### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by gtikhonov** [gtikhonov/HMSC#1]
Artificial "test" issue that I created to demonstrate the mechanic to @ovaskain.

**Comment by ovaskain** [comment]
Looks like I am able to post a comment

**Comment by gtikhonov** [comment]
We just had a chat with Tanja and we agreed that it would be beneficial in long-term to go towards this choice straightaway even for our internal course. So, maybe, you could add to the information circulated through email that to actively participate in discussion, e.g. posting a comment, one must be logged in to his/her GitHub account. Many researchers already have one, and it is really easy and fast to create a new one (which you can also mention in the circulated info).

**Comment by gtikhonov** [comment]
Just checked how closing-reopening issues worked.
