### ISSUE TITLE
Could not find function "as.HMSCdata"

### ISSUE THREAD

**Issue by maxfarrell** [gtikhonov/HMSC#6]
I'm trying to work through the examples from  (https://www.helsinki.fi/sites/default/files/atoms/files/hmsc_manual_0.pdf).
I seem to have successfully installed the package (aside from a failed to assign RegisteredNativeSymbol for toeplitz error)

However, when I work through the example I immediately run into the error that "as.HMSCdata" cannot be found. 

I'm working with Hmsc_0.2.11.3 installed from here, and R version 3.2.3

**Comment by gtikhonov** [comment]
@maxfarrell, please check that you are using the "right" HMSC repo: the correct repo that is covered by that manual is [here](https://github.com/guiblanchet/HMSC), and this repo contains ongoing development of completely redesigned and enhanced version.
